// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/railway-station-photos-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"admin_inbox | country | inbox | inbox_count | inbox_entry | inbox_state_query | o_auth_token | oauth | photo | photo_download | photo_station | photo_upload | photographer | profile | public_inbox | stat"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.RailwayStationPhotosSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "railway-station-photos_list",
		Description: "List records from RailwayStationPhotos. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "railway-station-photos_load",
		Description: "Load a single record from RailwayStationPhotos. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.RailwayStationPhotosSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.RailwayStationPhotosSDK, name string) (sdk.RailwayStationPhotosEntity, error) {
	switch strings.ToLower(name) {
	case "admin_inbox":
		return client.AdminInbox(nil), nil
	case "country":
		return client.Country(nil), nil
	case "inbox":
		return client.Inbox(nil), nil
	case "inbox_count":
		return client.InboxCount(nil), nil
	case "inbox_entry":
		return client.InboxEntry(nil), nil
	case "inbox_state_query":
		return client.InboxStateQuery(nil), nil
	case "o_auth_token":
		return client.OAuthToken(nil), nil
	case "oauth":
		return client.Oauth(nil), nil
	case "photo":
		return client.Photo(nil), nil
	case "photo_download":
		return client.PhotoDownload(nil), nil
	case "photo_station":
		return client.PhotoStation(nil), nil
	case "photo_upload":
		return client.PhotoUpload(nil), nil
	case "photographer":
		return client.Photographer(nil), nil
	case "profile":
		return client.Profile(nil), nil
	case "public_inbox":
		return client.PublicInbox(nil), nil
	case "stat":
		return client.Stat(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
